"""
Event module.

This module describes the types of events that can be generated by the daemon
and subsequently emitted to the clients.

"""

from reactor.message import Message

class Event(Message):
    """
    The base class for all events.
    """
    def to_dict(self):
        fields = self.__dict__.copy()
        fields['class'] = self.__class__.__name__
        fields['type'] = 'event'
        return fields 

class AdapterReady(Event):
    pass

class PluginReady(Event):
    pass

class ClientReady(Event):
    pass

class PacketReceived(Event):
    pass

class PacketDelivered(Event):
    pass

class PacketSent(Event):
    pass

class DeviceUpdated(Event):
    pass

class DeviceCreated(Event):
    pass

class DeviceDeleted(Event):
    pass



